version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/edushelf
      - static_volume:/usr/src/edushelf/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    restart: unless-stopped

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=bdedushelf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=petrova-05
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata:
  static_volume: