# Generated by Django 5.1.7 on 2025-03-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': False, 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
