# Generated by Django 5.1.7 on 2025-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0002_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
