# Generated by Django 5.2 on 2025-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
