# Generated by Django 5.1.7 on 2025-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0003_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
