# Generated by Django 5.1.7 on 2025-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0004_remove_user_email_user_encrypted_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
