# Generated by Django 5.1.7 on 2025-04-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0005_user_email_alter_user_encrypted_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookmarks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.AlterModelOptions(
            name='educationalinstitution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publishers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subjectspecialtylink',
            options={},
        ),
    ]
